# Generated by Django 5.1.2 on 2024-10-17 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='empdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('regno', models.IntegerField()),
                ('age', models.IntegerField()),
                ('yearofjoin', models.IntegerField()),
                ('mobile', models.IntegerField()),
                ('address', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='empuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=25)),
            ],
        ),
    ]
