# Generated by Django 5.1.2 on 2024-10-18 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empuser',
            name='password',
            field=models.CharField(max_length=250),
        ),
    ]
