# Generated by Django 5.1.2 on 2024-10-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_empdata_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empdata',
            name='mobile',
            field=models.CharField(max_length=15),
        ),
    ]
